"""empty message

Revision ID: 65d8f92ba4cd
Revises: 27bdd3dfb8fc
Create Date: 2025-10-28 16:31:35.692696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d8f92ba4cd'
down_revision = '27bdd3dfb8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('daily_price')
        batch_op.drop_column('date')
        batch_op.drop_column('is_available')
        batch_op.drop_column('booked_by_booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_by_booking_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('daily_price', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(None, 'bookings', ['booked_by_booking_id'], ['id'])
        batch_op.alter_column('room_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('reason')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
